<h3><?php echo __( 'Delete theme', THEME_DOMAIN ); ?></h3>
<p>
<?php echo __( 'Are you sure you want to delete the theme? ', THEME_DOMAIN ); ?>
"<span class="ttd-delete-skin-name"></span>"?
<?php echo __( 'This cannot be undone.', THEME_DOMAIN ); ?>
</p>

<div class="ttd-modal-footer">
<button class="ttd-left grey click" data-fn="close"><?php echo __( 'Cancel', THEME_DOMAIN ); ?></button>
<button class="ttd-right red click" data-fn="delete"><?php echo __( 'Delete theme', THEME_DOMAIN ); ?></button>
</div>
