<div class="ttd-tooltip ttd-homepage-confirmation-tooltip">

	<?php Thrive_Views::svg_icon( 'exclamation-circle' ); ?>

	<p class="ttd-tooltip-confirmation-text">
		<?php echo esc_attr__( 'Choosing a new homepage will permanently replace the one you had before', THEME_DOMAIN ); ?>
	</p>

	<span class="ttd-tooltip-confirmation-subtext">
		<?php echo esc_attr__( 'Are you sure you want to continue?', THEME_DOMAIN ); ?>
	</span>

	<div class="ttd-tooltip-buttons">
		<button class="ttd-normal-button blue-button click" data-fn="saveTemplate">
			<?php echo esc_attr__( 'Yes, replace my homepage', THEME_DOMAIN ); ?>
		</button>

		<button class="ttd-normal-button blue-button click" data-fn="closeConfirmation">
			<?php echo esc_attr__( 'No, keep my initial homepage', THEME_DOMAIN ); ?>
		</button>
	</div>
</div>
