<h3><?php echo __( 'Export templates', THEME_DOMAIN ); ?></h3>

<div class="modal-user-actions">
	<div class="ttd-export-name">
		<label class="default-text" for="export-archive-name"><?php echo __( 'Archive Name', THEME_DOMAIN ); ?></label>
		<input type="text" id="export-archive-name" placeholder="<?php echo __( 'Archive name', THEME_DOMAIN ); ?>" class="keyup" data-fn="keyup">
		<div class="ttd-error-message" style="display: none;">
			<?php echo sprintf( __( 'Please specify the name of the export archive.', THEME_DOMAIN ), '<span class="ttd-secondary-template-type"></span>' ); ?>
		</div>
	</div>
	<div class="ttd-templates-groups-list">

	</div>
</div>

<div class="ttd-modal-footer">
	<button class="ttd-left grey click" data-fn="close"><?php echo __( 'Cancel', THEME_DOMAIN ); ?></button>
	<button class="ttd-right red click" data-fn="export"><?php echo __( 'Export', THEME_DOMAIN ); ?></button>
</div>
