<h3><?php echo __( 'Import items', THEME_DOMAIN ); ?></h3>

<div class="modal-user-actions">
	<div class="ttd-import-templates-list-container">
		<h4><?php echo __( 'Templates', THEME_DOMAIN ); ?></h4>
		<button class="ttd-left click" data-type="templates" data-fn="select_all"><?php echo __( 'Select All', THEME_DOMAIN ); ?></button>
		<button class="ttd-right click" data-type="templates" data-fn="select_none"><?php echo __( 'Select None', THEME_DOMAIN ); ?></button>
		<div>
			<label class="tcb-checkbox">
				<input type="checkbox" class="s-post-type change" data-fn="select_import_extra" value="headers">
				<span><?php echo __( 'Import Headers', THEME_DOMAIN ); ?></span>
			</label>
			<label class="tcb-checkbox">
				<input type="checkbox" class="s-post-type change" data-fn="select_import_extra" value="footers">
				<span><?php echo __( 'Import Footers', THEME_DOMAIN ); ?></span>
			</label>
		</div>
		<div class="ttd-import-templates-list"></div>
	</div>
	<div class="ttd-import-symbols-list-container">
		<h4><?php echo __( 'Symbols', THEME_DOMAIN ); ?></h4>
		<div class="ttd-import-symbols-list"></div>
	</div>
</div>

<div class="ttd-modal-footer">
	<button class="ttd-left grey click" data-fn="close"><?php echo __( 'Cancel', THEME_DOMAIN ); ?></button>
	<button class="ttd-right red click" data-fn="import"><?php echo __( 'Import', THEME_DOMAIN ); ?></button>
</div>