<div class="fill pt-5" id="tcb-button-link-dynamic-control" data-view="DynamicLink" style="display:none">
	<select class="change dynamic-link-select"  data-fn="select_dynamic_link">
		<option value="#"><?php echo __( 'None', THEME_DOMAIN ); ?></option>
		<option value="thrive_the_permalink"><?php echo __( 'Post link', THEME_DOMAIN ); ?></option>
		<option value="thrive_archive_link"><?php echo __( 'Post Archive', THEME_DOMAIN ); ?></option>
		<option value="thrive_author_link"><?php echo __( 'Author Archive', THEME_DOMAIN ); ?></option>
		<option value="thrive_date_link"><?php echo __( 'Date link', THEME_DOMAIN ); ?></option>
		<option value="thrive_comments_link"><?php echo __( 'Comments link', THEME_DOMAIN ); ?></option>
	</select>
</div>