<div style='background-image: url("<#= this.model.get( 'thumb' ) #>")' class="ttd-cloud-skin-img"></div>
<div class="ttd-csn-container">
	<div class="ttd-cloud-skin-name"><#= this.model.get( 'name' ) #></div>
	<div class="ttd-cloud-buttons">
		<a target="_blank" href="<#= this.model.get( 'preview_url' ) #>" class="ttd-cloud-preview-btn"><?php echo __( 'Preview', THEME_DOMAIN ); ?></a>
		<div class="ttd-cloud-download-btn click" data-fn="<#= TTD.utils.isFreshInstall() ? 'skinSetupStep' : 'skinImportStep' #>">
			<# if( TTD.utils.isFreshInstall() ) { #>
			<?php echo __( 'Choose', THEME_DOMAIN ); ?>
			<# } else { #>
			<?php echo __( 'Download', THEME_DOMAIN ); ?>
			<# } #>
		</div>
	</div>
</div>
