<span class="logo-controls-row logo-<#=this.model.get('type')#>">
	<label><?php echo __( '<#= this.model.getDisplayName() #>', THEME_DOMAIN ); ?></label>

	<span class="click ttd-logo-reset <#= this.model.shouldHideReset() ? 'ttd-hide' : '' #>" data-fn="resetLogo">
		<?php echo __( 'Reset', THEME_DOMAIN ); ?>
	</span>

</span>
<button class="click logo-button logo-<#=this.model.get('type')#>" data-fn="openMedia"></button>
