<input class="tcb-condition-input-hour input" type="number" data-fn="hourChanged" min="<#= this.minHours #>" max="<#= this.maxHours #>">
<input class="tcb-condition-input-minute input" type="number" data-fn="minuteChanged" min="<#= this.minMinutes #>" max="<#= this.maxMinutes #>">
<a href="<?php echo admin_url( 'options-general.php' ) ?>" target="_blank" class="tcb-condition-input-timezone">UTC+<?php echo get_option( 'gmt_offset' ) ?></a>
